### PR TITLE
Use PSR-6 cache

### PR DESCRIPTION
**Pull request by amiranagram**
https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/824

### CODE REVIEW

**Comment by signmeuptwice** [comment]
@amiranagram Hello not sure if that is the place but I am still experiencing the issue 

      Problem 1
        - Root composer.json requires php-ffmpeg/php-ffmpeg ^0.18.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.18.0].
        - php-ffmpeg/php-ffmpeg v0.18.0 requires doctrine/cache ^1.0 -> found doctrine/cache[v1.0, ..., 1.12.1] but the package is fixed to 2.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

I tried `-W` but I get even more errors ... ??

I also tried
```

"require": {
  "php-ffmpeg/php-ffmpeg": "dev-psr"
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/ekyna/PHP-FFMpeg.git"
    }
],
```

my composer.json:

    {
        "type": "project",
        "license": "proprietary",
        "minimum-stability": "stable",
        "prefer-stable": true,
        "require": {
            "php": ">=8.1.0",
            "ext-ctype": "*",
            "ext-fileinfo": "*",
            "ext-gd": "*",
            "ext-iconv": "*",
            "ext-imagick": "^3.6",
            "ext-json": "*",
            "ext-openssl": "*",
            "doctrine/doctrine-bundle": "^2.5",
            "doctrine/doctrine-migrations-bundle": "^3.2",
            "doctrine/migrations": "^3.3",
            "doctrine/orm": "^2.10",
            "jms/serializer-bundle": "^4.0",
            "knplabs/knp-paginator-bundle": "^5.8",
            "laminas/laminas-code": "4.5.x-dev as 4.5.0",
            "symfony/asset": "6.0.*",
            "symfony/cache": "6.0.*",
            "symfony/config": "6.0.*",
            "symfony/console": "6.0.*",
            "symfony/dependency-injection": "6.0.*",
            "symfony/dotenv": "6.0.*",
            "symfony/flex": "^2",
            "symfony/framework-bundle": "6.0.*",
            "symfony/mailer": "6.0.*",
            "symfony/mime": "6.0.*",
            "symfony/runtime": "6.0.*",
            "symfony/twig-bundle": "6.0.*",
            "symfony/validator": "6.0.*",
            "symfony/web-profiler-bundle": "6.0.*",
            "symfony/yaml": "6.0.*"
        },
        "require-dev": {
            "symfony/maker-bundle": "^1.36",
            "symfony/var-dumper": "6.0.*"
        },
        "config": {
            "optimize-autoloader": true,
            "preferred-install": {
                "*": "dist"
            },
            "sort-packages": true
        },
        "autoload": {
            "psr-4": {
                "App\\": "src/"
            }
        },
        "autoload-dev": {
            "psr-4": {
                "App\\Tests\\": "tests/"
            }
        },
        "replace": {
            "symfony/polyfill-ctype": "*",
            "symfony/polyfill-iconv": "*",
            "symfony/polyfill-php72": "*",
            "symfony/polyfill-php73": "*",
            "symfony/polyfill-php74": "*",
            "symfony/polyfill-php80": "*"
        },
        "scripts": {
            "auto-scripts": {
                "cache:clear": "symfony-cmd",
                "assets:install %PUBLIC_DIR%": "symfony-cmd"
            },
            "post-install-cmd": [
                "@auto-scripts"
            ],
            "post-update-cmd": [
                "@auto-scripts"
            ]
        },
        "conflict": {
            "symfony/symfony": "*"
        },
        "extra": {
            "symfony": {
                "allow-contrib": false,
                "require": "6.0.*"
            }
        }
    }

**Comment by amiranagram** [comment]
@signmeuptwice Use my fork, I'm sure it will fix your issues.

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/AdaptechLLC/PHP-FFMpeg"
    }
],
"require": {
    "php-ffmpeg/php-ffmpeg": "dev-psr",
},
```

**Comment by amiranagram** [comment]
@signmeuptwice I hope the maintainers of `php-ffmpeg` will wake up from their coma.

**Comment by signmeuptwice** [comment]
@amiranagram Thank you for the suggestion however I still have the exact same issue with your repo; can I help ? I really hope the maintainers fix this issue too.

**Comment by amiranagram** [comment]
@signmeuptwice What error are you getting with our fork?

**Comment by signmeuptwice** [comment]
```
  Problem 1
    - Root composer.json requires php-ffmpeg/php-ffmpeg dev-psr -> satisfiable by php-ffmpeg/php-ffmpeg[dev-psr].
    - php-ffmpeg/php-ffmpeg dev-psr requires symfony/cache ^4.0 || ^5.0 -> found symfony/cache[v4.0.0, ..., v4.4.35, v5.0.0, ..., v5.4.0] but it conflicts with your root composer.json require (6.0.*).

```

**Comment by amiranagram** [comment]
@signmeuptwice Yeah, well you have `symfony/cache:6` in your project, and this fork uses `^4.0` or `^5.0`.

**Comment by signmeuptwice** [comment]
ok, thanks for the explanation; so I guess that makes it incompatible with Symfony 6 ?

**Comment by amiranagram** [comment]
@signmeuptwice I guess, I can bump it for you on `dev-psr` and see if everything works for you.

**Comment by amiranagram** [comment]
https://github.com/AdaptechLLC/PHP-FFMpeg/commit/41e785b590fa1361f0d3faeaf7726f815b1b7c96

**Comment by signmeuptwice** [comment]
@amiranagram thank you; I will try. do I still use the same command as before ?

**Comment by signmeuptwice** [comment]
@amiranagram  I tried with same command again and now I get this; looks like the maintainers have a big job on their hand ?

```
  Problem 1
    - alchemy/binary-driver 1.5.0 requires symfony/process ~2.0 -> found symfony/process[2.0.4, ..., v2.8.52] but these were not loaded, likely because it conflicts with another require.
    - alchemy/binary-driver 1.6.0 requires symfony/process ^2.0|^3.0 -> found symfony/process[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47] but these were not loaded, likely because it conflicts with another require.
    - alchemy/binary-driver[v2.0.0, 5.0.0, ..., v5.1.1] require symfony/process ^2.3|^3.0|^4.0 -> found symfony/process[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.35] but these were not loaded, likely because it conflicts with another require.
    - alchemy/binary-driver v5.2.0 requires symfony/process ^2.3|^3.0|^4.0|^5.0 -> found symfony/process[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.35, v5.0.0, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.
    - php-ffmpeg/php-ffmpeg dev-psr requires alchemy/binary-driver ^1.5 || ~2.0.0 || ^5.0 -> satisfiable by alchemy/binary-driver[1.5.0, 1.6.0, v2.0.0, 5.0.0, 5.1.0, v5.1.1, v5.2.0].
    - Root composer.json requires php-ffmpeg/php-ffmpeg dev-psr -> satisfiable by php-ffmpeg/php-ffmpeg[dev-psr].
```

**Pull request closed without merging**
